[theme]
primaryColor = "#2a5298"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8f9fa"
textColor = "#212529"
font = "sans serif"

[server]
maxUploadSize = 10
maxMessageSize = 10

[browser]
gatherUsageStats = false

[runner]
fastReruns = true